### ISSUE TITLE
Error: Validation Failed

### ISSUE THREAD

**Issue by arcuri82** [ScaCap/action-surefire-report#161]
Hi,
 trying to use this action. Added it with:

```
      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
```

however, no test report is created. I get the following in the logs of the action:

```
Result: 4522 tests run, 28 skipped, 6 failed.
Posting status 'completed' with conclusion 'failure' to refs/heads/minimize (sha: d343f8acf441370d10b7c74c4bad42f46c2fd404)
Error: Validation Failed: {"resource":"CheckRun","code":"invalid","field":"annotations"}
```

currently running on a branch. Am I doing something wrong? or is it a bug?

**Comment by ghaiszaher** [comment]
@arcuri82 is this easily reproducible on some public repository? I can only imagine that permissions are missing:
```yaml
    permissions:
      checks: write
      contents: read
    steps:
      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
```

Also see https://github.com/ScaCap/action-surefire-report#example-usage

**Comment by arcuri82** [comment]
thanks for the reply. However, since I reported this issue I have been trying other alternatives as well, and in the end the following worked for me:

```
      - name: Publish Test Report
        if: success() || failure()
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
```

the repository I am using is [EvoMaster](https://github.com/EMResearch/EvoMaster), which is public
