### ISSUE TITLE
Maven failsafe plugin reports parsing fails: [Error: Cannot read properties of undefined (reading 'testsuite')]

### ISSUE THREAD

**Issue by dejan-stojadinovic** [ScaCap/action-surefire-report#184]
Configuration:
```
    - name: Publish Failsafe Test Report
      if: success() || failure()
      uses: scacap/action-surefire-report@v1.7.2
      with:
        report_paths: "**/failsafe-reports/*.xml"
```

Maven plugin version: 
```
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <version>3.1.2</version>
                    </plugin>
```

Github Actions workflow error:

```
Run scacap/action-surefire-report@v1.7.2
  with:
    report_paths: **/failsafe-reports/*.xml
    github_token: ***
    create_check: true
    check_name: Test Report
    fail_on_test_failures: false
    fail_if_no_tests: true
    skip_publishing: false
    file_name_in_stack_trace: false
  env:
    ECR_AWS: *************
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.8-1/x64
    JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.8-1/x64
Going to parse results form **/failsafe-reports/*.xml
Error: Cannot read properties of undefined (reading 'testsuite')
```

Note: can't share code, repository is private.

**Comment by robbie-cronometer** [comment]
Also encountering the same issue: 

```
        steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Server Integration Tests
      run: mvn --errors --debug verify <REDACTED>
    - name: Report Test Results
      if: success() || failure()
      uses: scacap/action-surefire-report@v1
      with:
        report_paths: cronometer-server/target/failsafe-reports/*.xml
```

Maven Plugin version: 
`<maven.plugins.version>3.0.0</maven.plugins.version>`


Same error as previous
