### ISSUE TITLE
When run on `workflow_dispatch`, no `Test Report` appears

### ISSUE THREAD

**Issue by lobodpav** [ScaCap/action-surefire-report#199]
I have a workflow defined that allows running on `push` action and allows `manual` execution too.

When run on `push`, everything works fine. When run manually (i.e. on `workflow_dispatch`), no `Test Report` job appears and annotations are missing too.

What am I doing wrong?

```yaml
name: My workflow

on:
  push:
    branches:
      - dev
  workflow_dispatch:


jobs:
  build:
    name: Build and verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: ./mvnw -B verify -T 1C

      - name: Publish test reports
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1.7.3
        with:
          report_paths: '**/surefire-reports/*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
```
