### ISSUE TITLE
Instead of recommending `maven.test.failure.ignore`, use always() for publish test reports

### ISSUE THREAD

**Issue by ivangreene** [ScaCap/action-surefire-report#41]
Instead of ignoring the test failures in the stage where the tests are run, it may be better to recommend that the `if: ${{ always() }}` condition for the Publish Test Report stage.

This is especially true for builds where the tests are run as part of a stage that also publishes a snapshot artifact, and having the tests fail should mean that the snapshot should not be published. It's also worth noting that the example usage will 'pass' a build even if tests fail (it isn't using the `fail_on_test_failures` option)

Example with if always():
```yaml
name: build
on:
  pull_request:

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Build and Run Tests
        run: mvn test --batch-mode
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```
