### ISSUE TITLE
I got "Parameter token or opts.auth is required" at the end of run.

### ISSUE THREAD

**Issue by xw185019-ncr** [ScaCap/action-surefire-report#63]
hi, I uses "ScaCap/action-surefire-report@v1.0.5" after my maven test.

but for some reason, the github actions for my repo always report "Parameter token or opts.auth is required" error. 

i try put GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} into my yml, but github complain GITHUB_TOKEN is not allowed. :(

here is code snipper

```
    - name: Build cxth-wasp without tests
      run: mvn clean install -DskipTests=true -DskipIntegrationTests=true #skip all tests first to speed up the build process at the moment
    - name: Run unit test against wasp
      run: mvn test --fail-at-end
    - name: Surefire Report
      uses: ScaCap/action-surefire-report@v1.0.5
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
```

**Comment by jmisur** [comment]
Hi, the params might be very well case sensitive, try `github_token`.

FYI You can also just use release tag `ScaCap/action-surefire-report@v1` which always points to the latest v1 version. 

BTW I think gh actions can supply github token automatically, there is a default value for the variable.

**Comment by LordRekishi** [comment]
Hi, we also got this problem on our school projekt when trying to run it together with a maven build. We are not sure if we made some mistake in our .yml file or what this error actually means in reality.

Here is our current `maven.yml` file used for checking tests and such:

```
name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B test --file pom.xml
    - name: Surefire Report
      uses: ScaCap/action-surefire-report@v1.0.5

```
