### ISSUE TITLE
Error: request to https://api.github.com/repos/xxx/check-runs failed, reason: tunneling socket could not be established, statusCode=407

### ISSUE THREAD

**Issue by liu-shaojun** [ScaCap/action-surefire-report#91]
Hi experts, 
I'm running job in the self-hosted runners, when I use scacap/action-surefire-report@v1 to publish report, I always get the error `Error: request to https://api.github.com/repos/intel-analytics/BigDL/check-runs failed, reason: tunneling socket could not be established, statusCode=407` https://github.com/intel-analytics/BigDL/runs/7790266534?check_suite_focus=true

```
    - name: Publish Test Report
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1
      with:
        check_name: Example mvn Report
        report_paths: scala/dllib/target/surefire-reports/*.xml
```

![image](https://user-images.githubusercontent.com/61072813/184771713-3145eef2-0be8-49b9-b597-c3f77b36cc27.png)

I tried to add env to set the proxy then I got `Error: request to https://api.github.com/repos/intel-analytics/BigDL/check-runs failed, reason: connect ETIMEDOUT 140.82.114.6:443` https://github.com/intel-analytics/BigDL/runs/7836407257?check_suite_focus=true 

```
    - name: Publish Test Report
      env:
        https_proxy: http://xxx.com:913
        http_proxy: http://xxx.com:913
        no_proxy: api.github.com
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1
      with:
        check_name: Example mvn Report
        github_token: ${{ secrets.GITHUB_TOKEN }}
        report_paths: scala/dllib/target/surefire-reports/TEST*.xml
```
![image](https://user-images.githubusercontent.com/61072813/184775128-75c5fdd5-9332-42f3-926c-31d1308f4bbc.png)

Where could the problem be?
